# Generated by Django 4.2.7 on 2023-12-03 19:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='donor_photo',
            field=models.ImageField(default=1, upload_to='donor_photos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donor',
            name='home_address',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
