# Generated by Django 4.2.7 on 2023-12-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_donor_donor_photo_alter_donor_home_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='donor_photo',
            field=models.ImageField(blank=True, null=True, upload_to='donor_photos/'),
        ),
    ]
