# Generated by Django 4.2.7 on 2024-01-14 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_institutionbranch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='received_from',
        ),
    ]
