# Generated by Django 4.2.7 on 2024-01-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_donation_received_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_receipt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
