# Generated by Django 4.2.7 on 2024-01-14 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_donation_donation_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='institutionBranch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.institutionbranch'),
        ),
    ]
