# Generated by Django 4.2.7 on 2023-12-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_donor_donor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='donor_photo',
            field=models.ImageField(blank=True, null=True, upload_to='donor_photos/'),
        ),
    ]
