# Generated by Django 4.2.7 on 2024-01-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_donation_institutionbranch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='adhaar_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='pan_card_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
