# Generated by Django 4.2.7 on 2024-01-14 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_assets_institutionbranch_boy_child_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutionbranch',
            name='assets',
        ),
        migrations.CreateModel(
            name='InstitutionBranchAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.assets')),
                ('institution_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.institutionbranch')),
            ],
        ),
    ]
