# Generated by Django 4.2.7 on 2024-01-14 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_institutionbranch_assets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='quantity',
        ),
    ]
