# Generated by Django 4.2.7 on 2024-01-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_assets_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionbranch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Institution_Branch/'),
        ),
    ]
