# Generated by Django 4.2.7 on 2024-01-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_institutionbranch_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donation_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
