# Generated by Django 4.2.7 on 2024-01-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_donation_donation_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='product_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
