# Generated by Django 4.2.7 on 2024-05-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_donation_created_by_alter_donation_institution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
