# Generated by Django 4.2.7 on 2024-05-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_donor_email_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donation_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
