# Generated by Django 4.2.7 on 2024-06-08 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_donation_donation_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodInventoryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50)),
                ('items_details', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('last_month_balance', models.PositiveIntegerField()),
                ('items_received_from_other_centers', models.PositiveIntegerField()),
                ('items_from_donors', models.PositiveIntegerField()),
                ('purchased_items', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('items_given_to_kitchen', models.PositiveIntegerField()),
                ('items_sent_to_other_bases', models.PositiveIntegerField()),
                ('balance_due', models.PositiveIntegerField()),
                ('remarks', models.TextField()),
                ('institution', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('month', models.CharField(max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
