# Generated by Django 4.2.7 on 2024-06-08 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_foodinventorylist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodinventorylist',
            name='institution',
        ),
        migrations.AddField(
            model_name='foodinventorylist',
            name='institutionBranch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.institutionbranch'),
        ),
    ]
