# Generated by Django 4.2.7 on 2024-06-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_foodinventorylist_institution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodinventorylist',
            name='quantityUnit',
            field=models.CharField(default='kg', max_length=50),
            preserve_default=False,
        ),
    ]
