# Generated by Django 4.2.7 on 2024-06-08 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_foodinventorylist_quantityunit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodinventorylist',
            old_name='quantityUnit',
            new_name='quantity_Unit',
        ),
    ]
