# Generated by Django 4.2.7 on 2024-08-19 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_quantityunit_foodinventorylist_quantity_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='describe_towards',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='other_product_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='quantity_unit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='transaction_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='towards',
            field=models.CharField(choices=[('food', 'Food'), ('clothing', 'Clothing'), ('education', 'Education'), ('others', 'Others')], max_length=20),
        ),
    ]
