# Generated by Django 5.0.11 on 2025-02-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_institutionbranch_monthly_invoice_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='phone_no',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='institutionbranch',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='institutionbranch',
            name='phone_no',
            field=models.CharField(max_length=15),
        ),
    ]
